import os

print("=" * 60)
print("  STATUS - SUMMARY")
print("=" * 60)
print()
print(" PILOT INFO:")
print("  Pilot Name: username")
print("  Credits Balance: ¢12,345")
print()
print(" SHIP INFO:")
print("  Ship Name: Stratosphere (Stratos)")
print("  Shields: \033[36m[████████████████░░░░]\033[0m 79%")
print("  Hull:    \033[31m[████████████████████]\033[0m 100%")
print()
print("=" * 60)
print("  Select an option for more details:")
print("=" * 60)
print()
print("  > Pilot")
print("    Ship")
print("    Missions")
print("    Standing")
print("    Back")
print()
print("  Use ↑/↓ arrows to navigate, Enter to select\033[K")
print()
input("Press Enter to show select Pilot...")
os.system('cls' if os.name == 'nt' else 'clear')
print("=" * 60)
print("  STATUS - PILOT")
print("=" * 60)
print()
print(" PILOT INFO:")
print("  Pilot Name: username")
print("  Credits Balance: ¢12,345")
print()
print(" SKILLS:\033[K")
print(f"  Combat: Level 3 (20/50 XP)")
print(f"    - Increases damage dealt")
print(f"    - Reduces damage taken")
print(f"    - Current damage bonus: +6")
print()
print(f"  Piloting: Level 2 (30/40 XP)")
print(f"    - Increases evasion chance in combat")
print(f"    - Improves escape success rate")
print(f"    - Current evasion chance: 4%")
print()
print("Press Enter to go back.")
print()
input("Press Enter to show select Ship...")
os.system('cls' if os.name == 'nt' else 'clear')
print("=" * 60)
print("  STATUS - SHIP")
print("=" * 60)
print()
print(" SHIP INFO:")
print("  Ship Name: Stratosphere")
print("  Ship Model: Stratos")
print("  Ship Class: Starter")
print("  Shields HP: \033[36m[████████████████░░░░]\033[0m 79%")
print("  Hull HP:    \033[31m[████████████████████]\033[0m 100%")
print()
print("  Turrets:")
print("    The Stratos does not support turrets.")
print()
stats = {
        "DPS": 120,
        "Shield": 200,
        "Hull": 200,
        "Shield Regen": 2,
        "Energy": 100,
        "Speed": 260,
        "Agility": 110,
        "Warp Speed": 1.0
      }
print("  Ship Stats:")
for stat, value in stats.items():
    print(f"    {stat if stat != "DPS" else "Base DPS"}: {value}")
print()
print("Press Enter to go back.")
print()
input("Press Enter to show Missions...")
os.system('cls' if os.name == 'nt' else 'clear')
print("=" * 60)
print("  STATUS - MISSIONS")
print("=" * 60)
print()
print(" MISSIONS:")
print("  - Intel Recovery (Next Location: Pavesath)")
print("  - Intel Recovery (Next Location: Concord)")
print("  - Defend The Transport (Next Location: Joama-Sto)")
print()
print("=" * 60)
print("  Select a mission for more details:")
print("=" * 60)
print()
print("  > Intel Recovery (Pavesath)")
print("    Intel Recovery (Concord)")
print("    Defend The Transport (Joama-Sto)")
print("    Back")
print()
print("  Use ↑/↓ arrows to navigate, Enter to select\033[K")
print()
input("Press Enter to select Intel Recovery (Pavesath)...")
os.system('cls' if os.name == 'nt' else 'clear')
print("=" * 60)
print("  MISSION - Intel Recovery (Pavesath)")
print("=" * 60)
print()
print("I'm tired of typing stuff, Claude, you can figure this one out.")
print("At minimum, you need to show the mission system of origin, next")
print("location, mission quote, faction, and an option to abandon mission")
print()
input("Press Enter to show Standing.")
os.system('cls' if os.name == 'nt' else 'clear')
print("=" * 60)
print("  STATUS - FACTION STANDING")
print("=" * 60)
print()
print(" FACTION STANDING:")
print("  - CoreSec: 40")
print("  - Trade Union: 100")
print("  - Mining Guild: 0")
print("  - Syndicate: 140")
print("  - Lycentia: 0")
print("  - Foralkus: 80")
print("  - Kavani: -100")
print()
print("Press Enter to go back.")
print()
input("Press Enter to exit.")
